name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry-intl.ap-southeast-3.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            registry-intl.ap-southeast-3.aliyuncs.com/wetix/openapi-doc:latest
            registry-intl.ap-southeast-3.aliyuncs.com/wetix/openapi-doc:${{ github.sha }}

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Deploy Release on cluster
        run: |
          echo ${{ secrets.K8S_KEY }} | base64 --decode --ignore-garbage > /tmp/config
          export KUBECONFIG=/tmp/config
          kubectl set image deployment openapi-doc openapi-doc=registry-intl-vpc.ap-southeast-3.aliyuncs.com/wetix/openapi-doc:${{ github.sha }} --namespace=default
